{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the configMap volume to the volumes */}}
{{- define "mosquitto.configVolume" -}}
enabled: "true"
mountPath: "/mosquitto/config/mosquitto.conf"
subPath: "mosquitto.conf"
type: "custom"
volumeSpec:
  configMap:
    name: {{ template "common.names.fullname" . }}-config
{{- end -}}
{{- $_ := set .Values.persistence "mosquitto-config" (include "mosquitto.configVolume" . | fromYaml) -}}

{{/* Append the configMap volume to the volumes */}}
{{- define "mosquitto.customConfigVolume" -}}
enabled: "true"
mountPath: /mosquitto/configinc/{{ .key }}
subPath: {{ .key }}
type: "custom"
volumeSpec:
  configMap:
    name: {{- .name -}}-custom-config-{{- .key | replace "." "-" -}}
{{- end -}}

{{- if .Values.customConfigmap.enabled }}
{{- range $key, $val := .Values.customConfigmap.data }}
{{ $data := dict "key" $key "val" $val "name" "mosquitto" }}
{{- $_ := set .Values.persistence "mosquitto-custom1" (include "mosquitto.customConfigVolume" $data | fromYaml) -}}
{{- end }}
{{- end }}

{{/* Render the templates */}}
{{ include "common.all" . }}
