apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels: {{- include "mosquitto.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:  
{{- if .Values.ingress.enabled }}
  {{- with .Values.ingress.hosts }}
  rules:
  {{- range $key, $value := . }}
    - host: {{ $value.host }}
      http:
        paths:
        - backend:
            service:
              name: {{ include "mosquitto.fullname" $ }}
              port: 
                number: {{ $value.port }}
          path: {{ default "/" $value.path }}
          pathType: Prefix
  {{- end }}
  {{- end }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
{{- end }}