{{- include "common.values.setup" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
    {{- if .Values.jwtAuth.enabled }}
    auth_plugin /mosquitto/jwt_auth.so
    {{- end }}
    per_listener_settings {{ .Values.perListenerSettings }}
    {{- if .Values.auth.enabled }}
    allow_anonymous false
    {{- else }}
    allow_anonymous true
    {{- end }}
    {{- if .Values.persistence.data.enabled }}
    persistence true
    persistence_location {{ .Values.persistence.data.mountPath }}
    autosave_interval 1800
    {{- end }}
    {{- if .Values.persistence.configinc.enabled }}
    include_dir {{ .Values.persistence.configinc.mountPath }}
    {{- end }}
    {{- range $key, $value := .Values.service.main.ports }}
    {{- if $value.enabled }}
    listener {{ $value.port }} {{ $value.host }}
    protocol {{ $value.appProtocol }}
    {{- end }}
    {{- end }}
    include_dir /mosquitto/configinc
