apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
  {{- include "mosquitto.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.service.annotations -}}
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end -}}
  {{- end -}}
spec:
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- with .Values.ports }}
  ports:
    {{- range $key, $value := . }}
    - name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $key }}
      protocol: {{ default "TCP" $value.protocol }}
  {{- end }}
  {{- end }}
  selector: {{- include "mosquitto.selectorLabels" . | nindent 4 }}
